### ISSUE TITLE
squareFourier is undefined.

### ISSUE THREAD

**Issue by alexvnesta** [kampidh/U8g2_Graphing#1]
Hi,

Does this depend on another package? I am using platformio and vscode and squareFourier used in your example is not a standard function.

could you add this function to your library?

Thanks,
Alex

**Comment by kampidh** [comment]
Hello,

squareFourier function is defined at the very end of the code in the example code provided, it's just a simple mathematical function and shouldn't depend on another package.

Maybe try to move the function above the others? Some compilers need forward declaration of the function though.

Edit:
Or maybe you want to use squareFourier outside the example? In that case you can simply copy the function from the example code.
